name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        env:
          REPOSITORY: ${{ github.repository }}
        run: |
          ls -la
          git clone "https://github.com/$REPOSITORY" .

      - name: Download Zola
        run: |
          version='v0.19.2'
          archive="zola-${version}-x86_64-unknown-linux-gnu.tar.gz"
          curl -L "https://github.com/getzola/zola/releases/download/${version}/${archive}" -o "$archive"
          tar xf "$archive"

      - name: Build the site
        run: |
          ./zola build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    name: Build and deploy the site
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
